.circleci/config.yml, .gitignore, graph-schemas/uniswap.graphql, graph-schemas/zora.graphql, package.json, yarn.lock
Fix testing environment and missing packages/files for circleci.
=> Circleci project setup

src/context/NFTFetchContext.tsx
=> manually import types for children element

src/fetcher/MediaFetchAgent.ts, src/fetcher/TransformFetchResults.ts, src/hooks/useCallbackFetch.ts, src/hooks/useNFT.ts, src/hooks/useNFTContent.ts, src/hooks/useNFTMetadata.ts, tests/TransformFetchResults.test.ts
update currency fixes adding in content type change updates and fixing eth currency resolution
fixes #13 and #14
=> allow dynamic hook arguments and fix eth currency resolutions

graph-schemas/get-schemas.sh, graph-schemas/zora.graphql, src/fetcher/AuctionInfoTypes.ts, src/fetcher/FetchResultTypes.ts, src/fetcher/MediaFetchAgent.ts, src/fetcher/TransformFetchResults.ts, src/graph-queries/zora-types.ts, src/graph-queries/zora.ts, tests/__snapshots__/useNFT.test.ts.snap, tests/setupZoraGQLMock.ts
1. fetch auctions from within subgraph
2. add in bid share information, normalize current bid logic and cleanup
3. add currency information to current bid
=> refactor fetching auction framework and cleaning up data model

src/constants/urls.ts, src/fetcher/FetchResultTypes.ts, src/fetcher/MediaFetchAgent.ts, src/hooks/useAuctions.ts, src/hooks/useZoraUsername.ts, src/index.ts, tests/useZoraUsername.test.ts
Fetches Zora username information from Zora for pretty display with client end-users
=> [feature] adding username hook

src/fetcher/AuctionInfoTypes.ts, src/fetcher/DataTransformers.ts, src/fetcher/OpenseaUtils.ts, src/hooks/useNFT.ts, src/hooks/useZNFT.ts, src/index.ts
This updates the transformation output for `useNFT` and `useZNFT`
=> refactoring initialData types for server fetch with both nft types

src/constants/networks.ts
=> match network id enum to chainid

graph-schemas/zora.graphql, package.json, src/graph-queries/zora-types.ts, src/graph-queries/zora.ts, src/hooks/useAuctions.ts, tests/__snapshots__/useAuctions.test.ts.snap, tests/__snapshots__/useOpenseaNFT.test.ts.snap, tests/__snapshots__/useZNFT.test.ts.snap
Adding some auction fields for linking transactions and providing more updated dates for "auction listed" events
=> [update schemas] adding fields for approval date and txnHash

src/fetcher/MediaFetchAgent.ts, src/fetcher/TransformFetchResults.ts, src/graph-queries/zora-types.ts, src/graph-queries/zora.ts, tests/__snapshots__/useZNFTGroup.test.ts.snap
This changes the structure from graphql to accomplish an OR query from thegraph.
=> fix for multiresponse query

src/fetcher/MediaFetchAgent.ts, src/fetcher/OpenseaUtils.ts, src/graph-queries/zora-types.ts, src/graph-queries/zora.ts, tests/__snapshots__/useAuctions.test.ts.snap, tests/__snapshots__/useOpenseaNFT.test.ts.snap, tests/__snapshots__/useZNFT.test.ts.snap, tests/__snapshots__/useZNFTGroup.test.ts.snap, tests/useOpenseaNFT.test.ts
This fixes loading multiple auction datas in at once
=> fixing data list multiple import bug

src/constants/networks.ts, src/constants/urls.ts
=> Adding polygon chain id

src/constants/urls.ts, src/graph-queries/zora-indexer.ts
https://hasura.io/docs/latest/graphql/cloud/response-caching.html
Based on this documentation we simply include @cached in the query - have added in the indexer specific queries.
=> added @cached to zora-indexer requests

CHANGELOG.md, src/graph-queries/zora-indexer.ts
Hide burned tokens from collection results
=> Feature: hide burned tokens from results

package.json, src/backends/opensea/OpenseaDataSource.ts, src/backends/zdk-alpha/ZDKAlphaDataSource.ts, src/backends/zora-graph/GraphAuctionDataSource.ts, src/backends/zora-indexer-v1/ZoraIndexerV1DataSource.ts, src/backends/zora-indexer-v1/zora-indexer.ts, yarn.lock
=> Artiva app fix auctions (moving from #85)

src/backends/ens-reverse/EnsReverseFetcher.ts, src/backends/ether-actor/EtherActorDataSource.ts, src/backends/opensea/OpenseaDataSource.ts, src/backends/zdk-alpha/ZDKAlphaDataSource.ts, src/backends/zora-graph/ZoraGraphDataSource.ts, src/backends/zora-indexer-v1/ZoraIndexerV1DataSource.ts, src/strategies/NFTStrategy.ts, src/types/NFTInterface.ts
* use camelCased variable types
* fix ENS
=> Refactor media handling types v1

src/backends/zora-indexer-v1/ZoraIndexerV1DataSource.ts
This fixes query ordering for asks for auction houses.
=> Fix querying asks v3

src/backends/opensea/OpenseaDataSource.ts, src/backends/zora-graph/ZoraGraphDataSource.ts, src/hooks/useNFT.ts
Fixes some small fetching issues with zora graph and opensea data sources. Also checks if strategy has secondary data before executing the query (was causing merge issues).
=> Fixes fetching issues

src/backends/ether-actor/EtherActorDataSource.ts, src/backends/opensea/OpenseaDataSource.ts, src/backends/zdk-alpha/ZDKAlphaDataSource.ts, src/backends/zora-graph/ZoraGraphDataSource.ts, src/backends/zora-indexer-v1/ZoraIndexerV1DataSource.ts, src/strategies/NFTStrategy.ts, src/types/NFTInterface.ts
=> Add fixed price address & remove Nullable

src/types/NFTInterface.ts
Creates a market source for foundation fixed prices
=> Adds foundation market source

src/backends/zdk/ZDKDataSource.ts, yarn.lock
This batches hooks requests to the ZDK.
=> Add data fetcher deduping on zdk

.gitignore, package.json, src/backends/zdk/ZDKDataSource.ts, src/backends/zdk/transformUtils/transformEvents.ts, src/backends/zdk/transformUtils/transformMarketEvent.ts, src/backends/zdk/transformUtils/transformMarkets.ts, src/hooks/useNFT.ts, tsconfig.json, yarn.lock
we need `transofrmEvents` for dotco
=> export tranfrom functions and monkey-patch api bug

package.json, src/backends/zdk/transformUtils/transformEvents.ts, src/backends/zdk/transformUtils/transformMarketEvent.ts, src/backends/zdk/transformUtils/transformMarkets.ts, src/backends/zdk/transformUtils/transformMintEvent.ts, src/backends/zdk/transformUtils/transformTransferEvent.ts, src/backends/zdk/transformUtils/transformV1MarketEvent.ts, src/backends/zdk/transformUtils/transformV2AuctionEvent.ts, src/backends/zdk/transformUtils/transformV3AskEvent.ts, src/types/NFTInterface.ts, yarn.lock
- updated to latest zdk
- moved data event transformation functions into separate files
=> WIP move transform function into separate files
